version: '3.7'

volumes:
  db_data:

services:

  mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - db_data:/var/lib/mysql
      - .docker/database/db-dump:/docker-entrypoint-initdb.d
