#version: '3.7'
#
#volumes:
#  db_data_zeiterfassung:
#
#services:
#
#  database_zeiterfassung:
#    image: mysql:5.7
#    ports:
#      - 3309:3306
#    environment:
#      MYSQL_DATABASE: test_db
#      MYSQL_USER: test_user
#      MYSQL_PASSWORD: test
#      MYSQL_ROOT_PASSWORD: test
#    volumes:
#      - db_data_zeiterfassung:/var/lib/mysql
#      - .docker/database_zeiterfassung/db-dump:/docker-entrypoint-initdb.d
#
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    depends_on:
#      - database_zeiterfassung
#    links:
#      - database_zeiterfassung:database_zeiterfassung
#    ports:
#      - 4089:80
#    environment:
#      PMA_HOST: database_zeiterfassung
#
#  web:
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - database_zeiterfassung
#    links:
#      - database_zeiterfassung:database_zeiterfassung
#    ports:
#      - 8089:8089
#    environment:
#      MYSQL_HOST: database_zeiterfassung
#      MYSQL_DATABASE: test_db
#      MYSQL_USER: test_user
#      MYSQL_PASSWORD: test
#      MYSQL_ROOT_PASSWORD: test