version: '3.7'

volumes:
  db_data:

services:

  database:
    image: mysql:5.7
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - db_data:/var/lib/mysql
      - .docker/database/db-dump:/docker-entrypoint-initdb.d

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    depends_on:
#      - database
#    links:
#      - database:database
#    ports:
#      - 4089:80
#    environment:
#      PMA_HOST: database
#
#  web:
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - database
#    links:
#      - database:database
#    ports:
#      - 8089:8089
#    environment:
#      MYSQL_HOST: database
#      MYSQL_DATABASE: test_db
#      MYSQL_USER: test_user
#      MYSQL_PASSWORD: test
#      MYSQL_ROOT_PASSWORD: test